# Generated by Django 5.1 on 2024-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
